#version: 2.1
#orbs:
# node: circleci/node@3.0.0
#workflows:
#  node-tests:
#    jobs:
#      - node/test
#
version: 2
jobs:
  build:
    machine: true

    working_director: .

    steps:
      -checkout

      -run:
        name: Build Docker Image
        command: docker build -t ricardomessiasferreira/api-softexpert:v2 .

      -run:
        name: Push to DockerHub
        command: |
          docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
          docker push ricardomessiasferreira/api-softexpert:v2