version: 2.0
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.1-node
        auth:
          username: $DOCKERHUB_LOGIN
          password: $DOCKERHUB_PASSWORD 

    steps:
      -checkout

      -run:
        name: Build Docker Image
        command: docker build -t $DOCKERHUB_LOGIN/$CIRCLE_PROJECT_REPONAME:v$CIRCLE_BUILD_NUM .

      -run:
        name: Push to DockerHub
        command: |
          docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
          docker push $DOCKERHUB_LOGIN/$CIRCLE_PROJECT_REPONAME:v$CIRCLE_BUILD_NUM